[project]
name = "gen"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "gitpython",
  "arghandler",
  "pexpect",
  "PyGithub",
  "gidgethub[httpx]",
  "async_property",
  "tabulate",
]

[dependency-groups]
dev = [
    "ty>=0.0.1a25",
]
